- get name and age of enum value
AndrewQA88/AQAMentoring pull request #2
Opened 2021-10-16 14:40 UTC by AndrewQA88

- get name and age of enum value
- get all values from enum (values)

2021-10-19 13:02 UTC, AndrewQA88 commented on src/test/java/exercises/Iryna.java
> +    IRA("Ira", 30), IRYNA("Iryna", 30), IRUSYA("Irusya", 30);
Updated:
`public enum ContactInformation {
    IRA("Ira", 30),
    JHON("Jhon", 35),
    JACK("Jack", 49);`

2021-10-20 09:49 UTC, iikarak requested changes

2021-10-20 09:49 UTC, iikarak commented on src/test/java/exercises/ContactInformation.java
> +    private final String name;
remove final

2021-10-20 09:49 UTC, iikarak commented on src/test/java/exercises/ContactInformation.java
> +    IRA("Ira", 30),
what if you know person name but don`t know age?

2021-10-20 09:49 UTC, iikarak commented on src/test/java/exercises/ContactInformation.java
> +        this.name = name;
return based on name that is String enum value of ContactInformation

2021-10-20 12:31 UTC, AndrewQA88 commented on src/test/java/exercises/ContactInformation.java
> +        this.name = name;
done

2021-10-20 12:32 UTC, AndrewQA88 commented on src/test/java/exercises/ContactInformation.java
> +    private final String name;
done

2021-10-27 12:04 UTC, merged