- classes human/employee.
AndrewQA88/AQAMentoring pull request #7
Opened 2021-10-28 21:04 UTC by AndrewQA88

- calculate age, job experience, age when got a job.

2021-11-03 13:20 UTC, iikarak requested changes

2021-11-03 13:20 UTC, iikarak commented on src/test/java/humanemployeeexercise/Employee.java
> +        return ChronoUnit.YEARS.between(birthDate, currentDate);
currentDate.getYear-birthDate.getYear
check is current Month is  after birth month
and the same for date

2021-11-03 13:20 UTC, iikarak commented on src/test/java/humanemployeeexercise/Employee.java
> +        return ChronoUnit.YEARS.between(hiringDate, currentDate);
is difference if you ask job expirirence that was on some date or will be in some future date and for now
for now to  check current expirince jut use here directly ZonedDateTime.now()

2021-11-03 13:20 UTC, iikarak commented on src/test/java/humanemployeeexercise/Employee.java
> +    public long ageOfEmployee(ZonedDateTime birthDate, ZonedDateTime currentDate) {
getAgeOfEmployee with out parameters

2021-11-03 15:23 UTC, AndrewQA88 commented on src/test/java/humanemployeeexercise/Employee.java
> +        return ChronoUnit.YEARS.between(hiringDate, currentDate);
changed directly to ZonedDateTime.now()

2021-11-03 15:48 UTC, AndrewQA88 commented on src/test/java/humanemployeeexercise/Employee.java
> +    public long ageOfEmployee(ZonedDateTime birthDate, ZonedDateTime currentDate) {
replace parameters with getAgeOfEmployee and getDateOfEmployment() directly in method

2021-11-03 21:27 UTC, AndrewQA88 commented on src/test/java/humanemployeeexercise/Employee.java
> +        return ChronoUnit.YEARS.between(birthDate, currentDate);
public long jobExperience() {
        if (ZonedDateTime.now().getMonth().getValue() == getDateOfEmployment().getMonth().getValue()
                && ZonedDateTime.now().getDayOfMonth() < getDateOfEmployment().getDayOfMonth()) {
            return (ZonedDateTime.now().getYear() - getDateOfEmployment().getYear() - 1);
        } else if (ZonedDateTime.now().getMonth().getValue() < getDateOfEmployment().getMonth().getValue()) {
            return (ZonedDateTime.now().getYear() - getDateOfEmployment().getYear() - 1);
        } else {
            return ZonedDateTime.now().getYear() - getDateOfEmployment().getYear();
        }
    }

2021-11-05 14:03 UTC, iikarak requested changes

2021-11-05 14:03 UTC, iikarak commented on src/test/java/humanemployeeexercise/Employee.java
> +        long fullYears = ZonedDateTime.now().getYear() - getBirthDate().getYear();
for counting of amount of full years based on date please create one function and use it in all places where it is requred, in order to not have code duplictaion

2021-11-05 14:03 UTC, iikarak commented on src/test/java/humanemployeeexercise/Employee.java
> +        if ((getDateOfEmployment().getMonth().getValue() < getBirthDate().getMonth().getValue())
please review comparison operators that we have in java to form smaller condition inside if check statement

2021-11-05 14:03 UTC, iikarak commented on src/test/java/humanemployeeexercise/Human.java
> +    private final ZonedDateTime birthDate;
good usage of final

2021-11-05 14:03 UTC, iikarak commented on src/test/java/humanemployeeexercise/Creature.java
> +    int getWeight();
add default function into interface as was requeted in task description

2021-11-05 18:04 UTC, AndrewQA88 commented on src/test/java/humanemployeeexercise/Creature.java
> +    int getWeight();
default void getMeaning(){
        System.out.println("Creature: something created either animate or inanimate.");
    }

2021-11-09 14:20 UTC, AndrewQA88 commented on src/test/java/humanemployeeexercise/Employee.java
> +        if ((getDateOfEmployment().getMonth().getValue() < getBirthDate().getMonth().getValue())
done

2021-11-12 13:26 UTC, iikarak requested changes

2021-11-12 13:26 UTC, iikarak commented on src/test/java/humanemployeeexercise/Employee.java
> +        return calculateFullYear(currentDate, getBirthDate());
use just variable of class with out get

2021-11-12 13:26 UTC, iikarak commented on src/test/java/humanemployeeexercise/Employee.java
> +    public long jobExperience() {
rename functions who have return type not void

2021-11-12 13:26 UTC, iikarak commented on src/test/java/humanemployeeexercise/Human.java
> +
@Override

2021-11-12 13:26 UTC, iikarak commented on src/test/java/humanemployeeexercise/Human.java
> +        return this.GREETING + "\n" + "Name: " + this.name;
add print whole info

2021-11-12 13:26 UTC, iikarak commented on src/test/java/humanemployeeexercise/Employee.java
> +        return this.GREETING + "\n" + "Name: " + super.getName() + "\n" + "Title: " + this.title;
use method toString from parent class

2021-11-12 13:26 UTC, iikarak commented on src/test/java/humanemployeeexercise/Employee.java
> +        this.vacation = ZonedDateTime.of(LocalDate.of(year, month, 1), LocalTime.of(0, 0), ZoneId.of("Europe/Helsinki"));
to not duplicate code, reuse here function with 3 parameters

2021-11-12 15:04 UTC, AndrewQA88 commented on src/test/java/humanemployeeexercise/Employee.java
> +        return calculateFullYear(currentDate, getBirthDate());
updated with getDateOfEmployment(), birthDate is the superclass's field

2021-11-12 15:08 UTC, AndrewQA88 commented on src/test/java/humanemployeeexercise/Employee.java
> +    public long jobExperience() {
done

2021-11-12 15:13 UTC, AndrewQA88 commented on src/test/java/humanemployeeexercise/Human.java
> +
done

2021-11-12 15:50 UTC, AndrewQA88 commented on src/test/java/humanemployeeexercise/Human.java
> +        return this.GREETING + "\n" + "Name: " + this.name;
done

2021-11-12 15:55 UTC, AndrewQA88 commented on src/test/java/humanemployeeexercise/Employee.java
> +        return this.GREETING + "\n" + "Name: " + super.getName() + "\n" + "Title: " + this.title;
done

2021-11-12 16:10 UTC, AndrewQA88 commented on src/test/java/humanemployeeexercise/Employee.java
> +        this.vacation = ZonedDateTime.of(LocalDate.of(year, month, 1), LocalTime.of(0, 0), ZoneId.of("Europe/Helsinki"));
public void setVacation(int year, int month) {
        setVacation(year, month, 1);
    }

2021-11-17 14:16 UTC, iikarak requested changes

2021-11-17 14:16 UTC, iikarak commented on src/test/java/humanemployeeexercise/Company.java
> +    public void allowance(Employee employee) {
try with update of int salary

2021-11-17 14:16 UTC, iikarak commented on src/test/java/humanemployeeexercise/Company.java
> +    public void allowance(Employee employee) {
allowance(int salary) {
salary+=500;
} 
salary?

2021-11-18 11:06 UTC, AndrewQA88 commented on src/test/java/humanemployeeexercise/Employee.java
> +        long fullYears = ZonedDateTime.now().getYear() - getBirthDate().getYear();
done

2021-11-24 15:44 UTC, iikarak commented on src/test/java/humanemployeeexercise/Company.java
> +    public void allowance(Employee employee) {
new Company().allowance(andriy.getSalary());
1-> allowance void -> no incrise
2-> allowance return int -> andriy.setSalary(new Company().allowance(andriy.getSalary()))

2021-12-10 16:05 UTC, iikarak approved these changes

2021-12-10 16:05 UTC, iikarak commented on src/test/java/humanemployeeexercise/Director.java
> +                throw new IncorrectAccessException("access denied");
with out try chatch

2021-12-10 16:05 UTC, iikarak commented on src/test/java/humanemployeeexercise/Director.java
> +        return -1;
INDEX_NOT_FOUND
org.apache.commons.lang3.StringUtils

2021-12-12 15:34 UTC, merged