- read file from resource
AndrewQA88/AQAMentoring pull request #8
Opened 2021-11-14 19:51 UTC by AndrewQA88

- add custom error message

2021-11-17 14:05 UTC, iikarak requested changes

2021-11-17 14:05 UTC, iikarak commented on src/test/java/exercises/filereader/ReadFileFromResources.java
> +        ClassLoader classLoader = getClass().getClassLoader();
update to have file inside folder in resources and don`t use full path, 
and read about File.separator why this is used?

2021-11-17 14:05 UTC, iikarak commented on src/test/java/exercises/filereader/ReadFileFromResources.java
> +        try (InputStreamReader streamReader = new InputStreamReader(is, StandardCharsets.UTF_8);
rewrite to not use try with resources

2021-11-18 10:04 UTC, AndrewQA88 commented on src/test/java/exercises/filereader/ReadFileFromResources.java
> +        ClassLoader classLoader = getClass().getClassLoader();
Updated:
- added folder
- used FileSeparator to create multiplatfor's paths

2021-11-18 11:02 UTC, AndrewQA88 commented on src/test/java/exercises/filereader/ReadFileFromResources.java
> +        try (InputStreamReader streamReader = new InputStreamReader(is, StandardCharsets.UTF_8);
added method with try - catch - finally

2021-11-24 15:37 UTC, iikarak approved these changes

2021-11-25 13:38 UTC, merged